const L={
  hrm:{n:'HRM Core',k:'HRM CORE',s:'Halifax Peninsula · Bedford · Dartmouth',
    core:[['Halifax Peninsula',44.6488,-63.5752],['Bedford',44.7318,-63.6619],['Dartmouth',44.6661,-63.5676]],
    micro:[['Clayton Park',44.6718,-63.6530],['Lower Sackville',44.7757,-63.6786],['Eastern Passage',44.6109,-63.4820]],bbox:[-63.80,44.48,-63.42,44.84]},
  moncton:{n:'Moncton',k:'MONCTON NB',s:'Downtown Moncton',core:[['Moncton',46.0878,-64.7782]],micro:[],bbox:[-64.95,45.98,-64.62,46.20]},
  shediac:{n:'Shediac',k:'SHEDIAC NB',s:'Shediac town centre',core:[['Shediac',46.2198,-64.5411]],micro:[],bbox:[-64.68,46.10,-64.40,46.34]}
};
const M=[['gem_hrdps_continental','HRDPS','ECCC',1.22],['gem_regional','GEM Regional','ECCC',1.12],['gem_seamless','GEM','ECCC',1.08],['ecmwf_ifs025','ECMWF IFS','ECMWF',1.08],['ecmwf_aifs025_single','ECMWF AIFS','ECMWF AI',1.04],['gfs_seamless','GFS','NOAA',1],['icon_seamless','ICON','DWD',.99],['ukmo_seamless','UKMO','UK Met',1.01],['meteofrance_seamless','Météo-France','France',.94],['jma_seamless','JMA','Japan',.9],['kma_seamless','KMA','Korea',.9],['bom_access_global','ACCESS-G','BOM',.86],['cma_grapes_global','GRAPES','CMA',.84]];
let loc=localStorage.getItem('wx-loc')||'hrm',token=0,lastUpdated=null,lastOfficial=null;
const avg=a=>{a=a.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null},med=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null},clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),fmt=(x,d=1)=>Number.isFinite(x)?x.toFixed(d):'--';
function robust(a){a=a.filter(Number.isFinite);if(!a.length)return null;if(a.length<4)return avg(a);let m=med(a),mad=med(a.map(x=>Math.abs(x-m)))||.5,keep=a.filter(x=>Math.abs(x-m)<=Math.max(1.4,3*mad));return avg(keep.length?keep:a)}
function icon(c){if(c===0)return'☀️';if([1,2].includes(c))return'🌤️';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if(c>=51&&c<=67)return'🌧️';if(c>=71&&c<=77)return'🌨️';if(c>=80&&c<=82)return'🌦️';if(c>=95)return'⛈️';return'⛅️'}
function idx(d){let n=new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Halifax',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).format(new Date()).replace(' ','T').slice(0,13),i=d.hourly.time.findIndex(t=>t.slice(0,13)>=n);return i<0?0:i}
function hourName(t){return new Intl.DateTimeFormat('en-CA',{hour:'numeric',timeZone:'America/Halifax'}).format(new Date(t+':00-03:00'))}function dayName(d){return new Intl.DateTimeFormat('en-CA',{weekday:'short',timeZone:'America/Halifax'}).format(new Date(d+'T12:00:00-03:00'))}function clock(t){if(!t)return'--';return new Intl.DateTimeFormat('en-CA',{hour:'numeric',minute:'2-digit',timeZone:'America/Halifax'}).format(new Date(t+':00-03:00'))}
function nav(){tabs.innerHTML=Object.entries(L).map(([k,v])=>`<button class="tab ${k===loc?'active':''}" data-k="${k}">${v.n}</button>`).join('');tabs.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{loc=b.dataset.k;localStorage.setItem('wx-loc',loc);nav();load()})}
function getSkills(){try{return JSON.parse(localStorage.getItem('wx-skills')||'{}')}catch{return{}}}function saveSkills(x){try{localStorage.setItem('wx-skills',JSON.stringify(x))}catch{}}function getLedger(){try{return JSON.parse(localStorage.getItem('wx-ledger-v6')||'[]')}catch{return[]}}function saveLedger(x){try{localStorage.setItem('wx-ledger-v6',JSON.stringify(x.slice(-1200)))}catch{}}
function skillFactor(id,lead=6){let s=getSkills()[`${loc}:${id}:${lead}`]||getSkills()[`${loc}:${id}:all`];if(!s||s.n<3)return 1;return clamp(1.35/(.75+s.mae),.62,1.30)}function regimeFactor(id,lead,windDir){let f=1;if(id==='gem_hrdps_continental'&&lead<=12)f*=1.10;if(id==='ecmwf_ifs025'&&lead>=24)f*=1.06;if((loc==='hrm'||loc==='shediac')&&Number.isFinite(windDir)&&windDir>=60&&windDir<=190&&id==='gem_hrdps_continental')f*=1.08;return f}function weightOf(m,lead,windDir){return m[3]*skillFactor(m[0],lead)*regimeFactor(m[0],lead,windDir)}
function weightedModel(mods,zname,getter,lead=0,windDir=null){let n=0,d=0;for(let x of mods.filter(x=>x.z[0]===zname)){let v=getter(x);if(!Number.isFinite(v))continue;let w=weightOf(x.m,lead,windDir);n+=v*w;d+=w}return d?n/d:null}function modelSpread(mods,zname,getter){let a=mods.filter(x=>x.z[0]===zname).map(getter).filter(Number.isFinite);return a.length?Math.max(...a)-Math.min(...a):null}
async function baseQ(z){let p=new URLSearchParams({latitude:z[1],longitude:z[2],timezone:'America/Halifax',forecast_days:7,temperature_unit:'celsius',wind_speed_unit:'kmh',current:'temperature_2m,apparent_temperature,relative_humidity_2m,wind_speed_10m,wind_gusts_10m,wind_direction_10m,weather_code',hourly:'temperature_2m,apparent_temperature,relative_humidity_2m,precipitation_probability,precipitation,weather_code,wind_speed_10m,wind_gusts_10m,wind_direction_10m,uv_index,shortwave_radiation',daily:'temperature_2m_max,temperature_2m_min,apparent_temperature_max,precipitation_probability_max,precipitation_sum,weather_code,sunrise,sunset,uv_index_max'});let r=await fetch('https://api.open-meteo.com/v1/forecast?'+p,{cache:'no-store'});if(!r.ok)throw Error(r.status);return{z,d:await r.json()}}
async function modelQ(z,m){let p=new URLSearchParams({latitude:z[1],longitude:z[2],timezone:'America/Halifax',forecast_days:7,temperature_unit:'celsius',current:'temperature_2m',hourly:'temperature_2m,precipitation',daily:'temperature_2m_max,temperature_2m_min',models:m[0]}),c=new AbortController(),tm=setTimeout(()=>c.abort(),7500);try{let r=await fetch('https://api.open-meteo.com/v1/forecast?'+p,{signal:c.signal,cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json();if(!d.hourly)throw Error('incomplete');return{z,m,d}}finally{clearTimeout(tm)}}
async function ecccObservation(){let C=L[loc],b=C.bbox,now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Halifax',year:'numeric',month:'numeric',day:'numeric'}).formatToParts(now).reduce((o,p)=>(o[p.type]=p.value,o),{}),filter=`properties.LOCAL_YEAR=${parts.year} AND properties.LOCAL_MONTH=${parts.month} AND properties.LOCAL_DAY=${parts.day}`,url=`https://api.weather.gc.ca/collections/climate-hourly/items?bbox=${b.join(',')}&limit=200&filter=${encodeURIComponent(filter)}&f=json`;try{let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(r.status);let j=await r.json(),fs=(j.features||[]).filter(x=>Number.isFinite(Number(x.properties?.TEMP)));fs.sort((a,b)=>Number(b.properties?.LOCAL_HOUR??-1)-Number(a.properties?.LOCAL_HOUR??-1));if(!fs.length)return null;let latest=Number(fs[0].properties.LOCAL_HOUR),same=fs.filter(x=>Number(x.properties.LOCAL_HOUR)===latest).slice(0,8);return{temp:robust(same.map(x=>Number(x.properties.TEMP)).filter(Number.isFinite)),hour:latest,station:same.map(x=>x.properties.STATION_NAME).filter(Boolean).slice(0,3).join(' · '),count:same.length}}catch{return null}}
async function ecccAlerts(){let b=L[loc].bbox,url=`https://api.weather.gc.ca/collections/weather-alerts/items?bbox=${b.join(',')}&limit=50&f=json`;try{let r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(r.status);let j=await r.json(),seen=new Map;for(let f of(j.features||[])){let p=f.properties||{},key=(p.alert_name_en||p.alert_short_name_en||p.id||'alert')+'|'+(p.feature_name_en||'');if(!seen.has(key))seen.set(key,p)}return[...seen.values()]}catch{return[]}}
function comfort(feel,hum,rain,uv,wind){let score=100;if(Number.isFinite(feel)){if(feel>31)score-=Math.min(45,(feel-31)*7);else if(feel>26)score-=Math.min(18,(feel-26)*3);else if(feel<8)score-=Math.min(30,(8-feel)*3)}if(hum>75&&feel>24)score-=10;if(rain>55)score-=20;else if(rain>30)score-=8;if(uv>7)score-=12;if(wind>35)score-=10;score=clamp(score,0,100);if(score>=78)return['Great outside',score,'var(--green)'];if(score>=58)return['Pretty good outside',score,'var(--green)'];if(score>=38)return['A bit uncomfortable',score,'var(--amber)'];return['Rough outside',score,'var(--red)']}
function laterAdvice(base){let b=base[0]?.d;if(!b)return'No guidance available yet.';let s=idx(b),a=[];for(let k=s;k<Math.min(s+12,b.hourly.time.length);k++){let feel=avg(base.map(x=>x.d.hourly.apparent_temperature?.[k])),rain=avg(base.map(x=>x.d.hourly.precipitation_probability?.[k])),uv=avg(base.map(x=>x.d.hourly.uv_index?.[k])),wind=avg(base.map(x=>x.d.hourly.wind_speed_10m?.[k])),hum=avg(base.map(x=>x.d.hourly.relative_humidity_2m?.[k])),c=comfort(feel,hum,rain,uv,wind);a.push({score:c[1],feel,rain,time:b.hourly.time[k]})}if(!a.length)return'No short-range guidance available.';let now=a[0],best=[...a].sort((x,y)=>y.score-x.score)[0];if(best.score>now.score+12)return`Better around ${hourName(best.time)} — feels near ${fmt(best.feel,0)}° with rain chance around ${fmt(best.rain,0)}%.`;if(now.rain>=45){let dry=a.find(x=>x.rain<25);if(dry)return`Rain risk drops after about ${hourName(dry.time)}.`}return'Conditions stay fairly similar over the next several hours.'}
function renderAlerts(a){alertCount.textContent=a.length;alertSummary.textContent=a.length?(a[0].alert_name_en||a[0].alert_short_name_en||'Weather alert'):'No active alerts found';if(a.length){alerts.style.display='block';alerts.innerHTML=`<b>${a[0].alert_name_en||a[0].alert_short_name_en||'Environment Canada alert'}</b>${a[0].feature_name_en||''}${a.length>1?` · +${a.length-1} more`:''}`}else alerts.style.display='none'}
function saveForecastTargets(mods){let ledger=getLedger(),stamp=Math.floor(Date.now()/3600000)*3600000,seen=new Set(ledger.map(e=>`${e.loc}|${e.model}|${e.lead}|${e.issued}`));for(let m of M){let rows=mods.filter(x=>x.m[0]===m[0]);for(let lead of[3,6,12,24]){let p=[];for(let x of rows){let s=idx(x.d),v=x.d.hourly.temperature_2m?.[s+lead];if(Number.isFinite(v))p.push(v)}let pred=avg(p),key=`${loc}|${m[0]}|${lead}|${stamp}`;if(Number.isFinite(pred)&&!seen.has(key))ledger.push({loc,model:m[0],lead,issued:stamp,target:stamp+lead*3600000,pred,scored:false})}}saveLedger(ledger.filter(e=>Date.now()-e.issued<10*86400000))}
function scoreDueForecasts(actual){if(!Number.isFinite(actual))return;let l=getLedger(),s=getSkills(),now=Date.now(),changed=false;for(let e of l){if(e.scored||e.loc!==loc||e.target>now+15*60000||now-e.target>5*3600000)continue;let err=Math.abs(e.pred-actual);for(let k of[`${loc}:${e.model}:${e.lead}`,`${loc}:${e.model}:all`]){let q=s[k]||{n:0,mae:0};q.mae=(q.mae*q.n+err)/(q.n+1);q.n++;s[k]=q}e.scored=true;e.err=err;changed=true}if(changed){saveSkills(s);saveLedger(l)}}
function render(base,mods,official,alertData,loading){if(!base.length)return;let C=L[loc],coreNames=new Set(C.core.map(z=>z[0])),coreBase=base.filter(x=>coreNames.has(x.z[0])),windDir=avg(coreBase.map(x=>x.d.current?.wind_direction_10m)),zs=C.core.map(z=>{let b=base.find(x=>x.z[0]===z[0]),i=b?idx(b.d):0,air=weightedModel(mods,z[0],x=>x.d.current?.temperature_2m,0,windDir);if(!Number.isFinite(air))air=b?.d.current?.temperature_2m;return{z,b,air,spread:modelSpread(mods,z[0],x=>x.d.current?.temperature_2m),feel:b?.d.current?.apparent_temperature,hum:b?.d.current?.relative_humidity_2m,wind:b?.d.current?.wind_speed_10m,gust:b?.d.current?.wind_gusts_10m,rain:b?.d.hourly?.precipitation_probability?.[i],uv:b?.d.hourly?.uv_index?.[i],fhigh:b?.d.daily?.apparent_temperature_max?.[0]}}),modelAir=avg(zs.map(x=>x.air)),obs=official?.temp,bias=Number.isFinite(obs)&&Number.isFinite(modelAir)?clamp(obs-modelAir,-3,3):0,air=Number.isFinite(modelAir)?modelAir+(Number.isFinite(obs)?.55:0)*bias:modelAir,providerFeel=avg(zs.map(x=>x.feel)),hum=avg(zs.map(x=>x.hum)),windV=avg(zs.map(x=>x.wind)),gust=avg(zs.map(x=>x.gust)),rainV=avg(zs.map(x=>x.rain)),uvV=avg(zs.map(x=>x.uv)),fhi=avg(zs.map